fix: fixing build errors
=== Build Errors ===
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.testcontainers:junit-jupiter:jar is missing. @ line 154, column 17
[ERROR] 'dependencies.dependency.version' for org.testcontainers:mysql:jar is missing. @ line 159, column 17
@
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.springframework.samples:spring-petclinic:3.3.0 (/home/jenkins/agent/workspace/branch-2026-08-10_20-04-5a44064a/pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for org.testcontainers:junit-jupiter:jar is missing. @ line 154, column 17
[ERROR]     'dependencies.dependency.version' for org.testcontainers:mysql:jar is missing. @ line 159, column 17
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1

GitHub has been notified of this commit’s build result

Finished: FAILURE
=======================