fix: fixing build errors
=== Build Errors ===
[ERROR] COMPILATION ERROR :
[ERROR] /home/jenkins/agent/workspace/n_temp-2026-02-19_21-58-79ecfbf1/src/main/java/org/springframework/samples/petclinic/system/LegacyHttpClient.java:[4,42] cannot find symbol
symbol:   class CloseableHttpClient
location: package org.apache.hc.client5.http.classic
[ERROR] /home/jenkins/agent/workspace/n_temp-2026-02-19_21-58-79ecfbf1/src/main/java/org/springframework/samples/petclinic/system/LegacyHttpClient.java:[16,17] cannot find symbol
symbol:   class CloseableHttpClient
location: class org.springframework.samples.petclinic.system.LegacyHttpClient
[ERROR] /home/jenkins/agent/workspace/n_temp-2026-02-19_21-58-79ecfbf1/src/main/java/org/springframework/samples/petclinic/system/LegacyHttpClient.java:[30,22] cannot find symbol
symbol:   method getStatusLine()
location: variable response of type org.apache.hc.client5.http.impl.classic.CloseableHttpResponse
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project spring-petclinic: Compilation failure: Compilation failure:
[ERROR] /home/jenkins/agent/workspace/n_temp-2026-02-19_21-58-79ecfbf1/src/main/java/org/springframework/samples/petclinic/system/LegacyHttpClient.java:[4,42] cannot find symbol
[ERROR]   symbol:   class CloseableHttpClient
[ERROR]   location: package org.apache.hc.client5.http.classic
[ERROR] /home/jenkins/agent/workspace/n_temp-2026-02-19_21-58-79ecfbf1/src/main/java/org/springframework/samples/petclinic/system/LegacyHttpClient.java:[16,17] cannot find symbol
[ERROR]   symbol:   class CloseableHttpClient
[ERROR]   location: class org.springframework.samples.petclinic.system.LegacyHttpClient
[ERROR] /home/jenkins/agent/workspace/n_temp-2026-02-19_21-58-79ecfbf1/src/main/java/org/springframework/samples/petclinic/system/LegacyHttpClient.java:[30,22] cannot find symbol
[ERROR]   symbol:   method getStatusLine()
[ERROR]   location: variable response of type org.apache.hc.client5.http.impl.classic.CloseableHttpResponse
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1

GitHub has been notified of this commit’s build result

Finished: FAILURE
=======================