fix: fixing build errors Fixes:             Fix build errors:
=== Build Errors ===
[ERROR] COMPILATION ERROR :
[ERROR] /home/jenkins/agent/workspace/ediation_branch-2025-06-06_14-10/src/main/java/org/springframework/samples/petclinic/owner/PetController.java:[73,32] incompatible types: org.springframework.samples.petclinic.owner.PetType cannot be converted to org.springframework.samples.petclinic.owner.Pet
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project spring-petclinic: Compilation failure
[ERROR] /home/jenkins/agent/workspace/ediation_branch-2025-06-06_14-10/src/main/java/org/springframework/samples/petclinic/owner/PetController.java:[73,32] incompatible types: org.springframework.samples.petclinic.owner.PetType cannot be converted to org.springframework.samples.petclinic.owner.Pet
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1

Could not update commit status, please check if your scan credentials belong to a member of the organization or a collaborator of the repository and repo:status scope is selected

GitHub has been notified of this commit’s build result

Finished: FAILURE
=======================